# Vivado Block Design Script (`bd.tcl`)

This folder contains the **Vivado IP Integrator Tcl script** used to recreate the block design that was employed during **hardware validation** of the IIR Biquad AXI-Stream module.

---

## Purpose

The `bd.tcl` script captures the **system-level integration context**, including:

* Zynq UltraScale+ MPSoC (KV260 preset)
* AXI DMA (MM2S / S2MM)
* AXI interconnect / SmartConnect
* Reset and clock topology
* Address map used during validation
* Connection of the `iir_biquad_axis` module

The intent is **documentation and reproducibility**, not convenience.

---

## Origin of the Script

* The script is **auto-generated by Vivado** using `write_bd_tcl`
* Tool version used: **Vivado 2024.1**
* The verbosity and structure reflect Vivado’s internal representation

This is intentional and preserved as-is.

---

## What This Script Is

* A record of **how the RTL was validated on real hardware**
* A reference for engineers who want to inspect:

  * AXI topology choices
  * DMA usage
  * PS–PL connectivity

---

## What This Script Is Not

* ❌ A minimal or clean example
* ❌ A portable build system
* ❌ A recommended starting point for new projects

Users are expected to already understand Vivado IP Integrator flows.

---

## Usage (Optional)

If you choose to source the script:

1. Open Vivado **2024.1**
2. Ensure `iir_biquad_axis.v` is already added to the project
3. Source the script from the Tcl console:

```
source bd.tcl
```

Paths or board presets may need adjustment depending on your environment.

---

## Relationship to the RTL

* The **RTL does not depend** on this script
* The repository remains usable without Vivado or PYNQ
* This script exists solely to document **integration decisions**

---

> This script documents system integration decisions, not system flexibility.
